language: java
branches:
  only:
  - master
before_install:
- curl --silent https://shunit2.googlecode.com/files/shunit2-2.1.6.tgz | tar xz -C
  /tmp/
- git clone https://github.com/ryanbrainard/heroku-buildpack-testrunner.git /tmp/testrunner
- "./etc/hatchet_travis_setup.sh"
install: true
script: eval $TEST_CMD
after_script: heroku keys:remove $USER@`hostname`
env:
  global:
  - HATCHET_RETRIES=3
  - HATCHET_DEPLOY_STRATEGY=git
  - HATCHET_BUILDPACK_BASE="https://github.com/heroku/heroku-buildpack-java.git"
  - SHUNIT_HOME="/tmp/shunit2-2.1.6"
  - secure: Gfyi0ZPwJQBdXSWVvUDFVmcqeLsNnVqIM2poke+Yg7PeBUUo78Hbn8coEXLWICqkzvESsVXNSGAqX70fueixe4P7LT7qCEy81XHV0VcXC72FuRUtKdUxdB1r+R9UiL8gwQDF1XdhlLoEneeT49XRNZqS2XzcDy2uHE5oWEND1vw=
  matrix:
  - TEST_CMD='[ "$TRAVIS_PULL_REQUEST" = "false" ] && mvn verify || true'
  - TEST_CMD="/tmp/testrunner/bin/run -c ."
