language: java

branches:
  only:
    - master

env:
  global:
    - IS_RUNNING_ON_TRAVIS=true
    - HATCHET_RETRIES=3
    - HATCHET_DEPLOY_STRATEGY=git
    - SHUNIT_HOME="/tmp/shunit2-2.1.6"
  matrix:
    - TEST_CMD="mvn verify"
    - TEST_CMD="/tmp/testrunner/bin/run -c ."

before_install:
  - curl --silent https://shunit2.googlecode.com/files/shunit2-2.1.6.tgz | tar xz -C /tmp/
  - git clone https://github.com/ryanbrainard/heroku-buildpack-testrunner.git /tmp/testrunner


script: $TEST_CMD
